-n Fixing dashboard-db uninstall

diff --git a/dashboard-db b/dashboard-db
--- a/dashboard-db
+++ b/dashboard-db
@@ -49,7 +49,11 @@ dashboard_db_uninstall() {
   fi
   sleep 10
 
-  cp -f config/database.example.yml config/database.yml
+  if [ "" != "${JOB_NAME}" ] ; then
+    cp -f config/database.ci.yml config/database.yml || die "Cannot copy DB config"
+  else
+    cp -f config/database.example.yml config/database.yml  || die "Cannot copy DB config"
+  fi
   rake db:drop
   if [ "" != "${JOB_NAME}" ] ; then
     rake db:drop RAILS_ENV=test
